# Generated by Django 3.1.4 on 2021-12-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electriclocomotive',
            old_name='max_usuable_energy',
            new_name='max_usable_energy',
        ),
    ]
