# Generated by Django 3.1.4 on 2021-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0002_auto_20211209_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='electriclocomotive',
            name='power_in',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='electriclocomotive',
            name='power_out',
            field=models.TextField(default='None'),
        ),
    ]
