# Generated by Django 3.1.4 on 2021-12-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0004_auto_20211209_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistrouteevaluation',
            name='ltd_analysis',
            field=models.BooleanField(default=True),
        ),
    ]
