# Generated by Django 3.1.4 on 2022-01-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0005_consistrouteevaluation_ltd_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='most_recent_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consist',
            name='most_recent_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consist',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
