# Generated by Django 3.1.4 on 2022-02-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0006_auto_20220126_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('nominal_voltage', models.FloatField(blank=True, null=True)),
                ('max_voltage', models.FloatField(blank=True, null=True)),
                ('min_operating_temperature', models.FloatField(blank=True, null=True)),
                ('max_operating_temperature', models.FloatField(blank=True, null=True)),
                ('cutoff_discharge_voltage', models.FloatField(blank=True, null=True)),
                ('cutoff_charge_voltage', models.FloatField(blank=True, null=True)),
                ('standard_current', models.FloatField(blank=True, null=True)),
                ('internal_resistance', models.FloatField(blank=True, null=True)),
                ('maximum_discharging_current', models.FloatField(blank=True, null=True)),
                ('minimum_charging_current', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('size_x', models.FloatField(blank=True, null=True)),
                ('size_y', models.FloatField(blank=True, null=True)),
                ('size_z', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('ocv_curve', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number_series_cells', models.IntegerField(blank=True, null=True)),
                ('number_parallel_cells', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bus_voltage', models.FloatField(blank=True, null=True)),
                ('max_voltage', models.FloatField(blank=True, null=True)),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.cell')),
                ('electric_locomotive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.electriclocomotive')),
            ],
        ),
    ]
