# Generated by Django 3.1.4 on 2022-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0008_auto_20220208_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cached_route_line',
            field=models.JSONField(null=True),
        ),
    ]
