# Generated by Django 3.1.4 on 2022-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0009_route_cached_route_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cached_route_line',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
