# Generated by Django 3.1.4 on 2022-02-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0010_auto_20220214_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('braking', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
