# Generated by Django 3.1.4 on 2022-02-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0012_consistrouteevaluation_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('created', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
            ],
        ),
    ]
