# Generated by Django 3.1.4 on 2022-03-03 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locomotives', '0013_userrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='nominal_voltage',
        ),
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('log_time', models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 20, 48, 992344, tzinfo=utc))),
                ('consist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.consist')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.route')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
