# Generated by Django 3.1.4 on 2022-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0014_auto_20220303_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='log_time',
            field=models.DateTimeField(),
        ),
    ]
