# Generated by Django 3.1.4 on 2022-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0017_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
