# Generated by Django 3.1.4 on 2022-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0019_consistrouteevaluation_result_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
