# Generated by Django 3.1.4 on 2022-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0020_auto_20220407_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consistrouteevaluation',
            name='policy',
        ),
        migrations.AddField(
            model_name='consistrouteevaluation',
            name='braking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consistrouteevaluation',
            name='power_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
