# Generated by Django 4.0.4 on 2022-05-10 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locomotives', '0020_auto_20220407_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTDResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('rapid', models.BooleanField(default=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result', models.JSONField(null=True)),
                ('consist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.consist')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('policy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locomotives.policy')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.route')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
