# Generated by Django 4.0.4 on 2022-05-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0021_auto_20220509_1716'),
        ('locomotives', '0022_ltdresults_status_alter_ltdresults_result_code'),
    ]

    operations = [
    ]
