# Generated by Django 4.0.4 on 2022-05-31 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0023_merge_20220531_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='power_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=3),
        ),
    ]
