# Generated by Django 4.0.4 on 2022-06-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0024_policy_power_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='power',
        ),
    ]
