# Generated by Django 4.0.4 on 2022-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0025_remove_policy_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='name',
        ),
        migrations.AddField(
            model_name='policy',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
