# Generated by Django 4.0.4 on 2022-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0026_remove_policy_name_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='max_speed',
            field=models.IntegerField(default=60),
        ),
    ]
