# Generated by Django 4.0.4 on 2022-06-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0027_policy_max_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='max_speed',
            field=models.FloatField(default=26.8224),
        ),
    ]
