# Generated by Django 4.0.4 on 2022-07-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0029_remove_ltdresults_group_remove_ltdresults_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powertowheels',
            name='ghg_co2_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
