# Generated by Django 4.0.4 on 2022-07-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0030_powertowheels_ghg_co2_emissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocomotiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('build_date', models.DateField(blank=True, null=True)),
                ('rebuild_date', models.DateField(blank=True, null=True)),
                ('test_data', models.DateField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.locomotivemodel')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.tier')),
            ],
        ),
        migrations.CreateModel(
            name='emissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_level', models.CharField(choices=[('N4', 'notch 4'), ('N6', 'notch 6'), ('LI', 'idle'), ('DB', 'dynamic brake'), ('N7', 'notch 7'), ('N3', 'notch 3'), ('N2', 'notch 2'), ('N5', 'notch 5'), ('N1', 'notch 1'), ('N8', 'notch 8')], max_length=20)),
                ('power', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField(blank=True, null=True)),
                ('ghg_hc_emissions', models.FloatField(blank=True, null=True)),
                ('ghg_co_emissions', models.FloatField(blank=True, null=True)),
                ('ghg_no_emissions', models.FloatField(blank=True, null=True)),
                ('ghg_pm_emissions', models.FloatField(blank=True, null=True)),
                ('ghg_co2_emissions', models.FloatField(blank=True, null=True)),
                ('LAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.lar')),
            ],
        ),
    ]
