# Generated by Django 4.1.1 on 2023-10-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0034_railroad_alter_batterymodule_id_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('DB', 'dynamic brake'), ('LI', 'idle'), ('N5', 'notch 5'), ('N4', 'notch 4'), ('N3', 'notch 3'), ('N1', 'notch 1'), ('N8', 'notch 8'), ('N2', 'notch 2'), ('N7', 'notch 7'), ('N6', 'notch 6')], max_length=20),
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.line')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.railroad')),
            ],
        ),
    ]
