# Generated by Django 4.1.1 on 2023-10-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0036_alter_emission_power_level_alter_yard_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N5', 'notch 5'), ('N6', 'notch 6'), ('N4', 'notch 4'), ('N3', 'notch 3'), ('N1', 'notch 1'), ('LI', 'idle'), ('N8', 'notch 8'), ('N7', 'notch 7'), ('N2', 'notch 2'), ('DB', 'dynamic brake')], max_length=20),
        ),
    ]
