# Generated by Django 4.1.1 on 2023-10-24 20:56

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0037_alter_emission_power_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='geometry',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='segment',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N7', 'notch 7'), ('N5', 'notch 5'), ('N2', 'notch 2'), ('N8', 'notch 8'), ('N6', 'notch 6'), ('N4', 'notch 4'), ('LI', 'idle'), ('N1', 'notch 1'), ('DB', 'dynamic brake'), ('N3', 'notch 3')], max_length=20),
        ),
    ]
