# Generated by Django 4.1.1 on 2023-10-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0038_line_geometry_line_segment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='yard',
            old_name='origin',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N8', 'notch 8'), ('N3', 'notch 3'), ('N6', 'notch 6'), ('N1', 'notch 1'), ('N4', 'notch 4'), ('N7', 'notch 7'), ('N5', 'notch 5'), ('N2', 'notch 2'), ('LI', 'idle'), ('DB', 'dynamic brake')], max_length=20),
        ),
        migrations.CreateModel(
            name='RouteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.line')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.route2')),
            ],
        ),
        migrations.AddField(
            model_name='route2',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinaton', to='locomotives.yard'),
        ),
        migrations.AddField(
            model_name='route2',
            name='line',
            field=models.ManyToManyField(through='locomotives.RouteLine', to='locomotives.line'),
        ),
        migrations.AddField(
            model_name='route2',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='locomotives.yard'),
        ),
        migrations.AddField(
            model_name='route2',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locomotives.railroad'),
        ),
    ]
