# Generated by Django 4.1.1 on 2023-10-26 18:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0039_route2_rename_origin_yard_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route2',
            name='line',
        ),
        migrations.AddField(
            model_name='route2',
            name='path',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N3', 'notch 3'), ('N6', 'notch 6'), ('N2', 'notch 2'), ('N1', 'notch 1'), ('N7', 'notch 7'), ('N8', 'notch 8'), ('N5', 'notch 5'), ('DB', 'dynamic brake'), ('LI', 'idle'), ('N4', 'notch 4')], max_length=20),
        ),
        migrations.DeleteModel(
            name='RouteLine',
        ),
    ]
