# Generated by Django 4.1.1 on 2023-10-30 14:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0040_remove_route2_line_route2_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='geometry',
            new_name='curvature',
        ),
        migrations.RenameField(
            model_name='line',
            old_name='segment',
            new_name='gradient',
        ),
        migrations.AddField(
            model_name='line',
            name='lnglat',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='xyz',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N7', 'notch 7'), ('N8', 'notch 8'), ('N3', 'notch 3'), ('LI', 'idle'), ('N2', 'notch 2'), ('N1', 'notch 1'), ('N5', 'notch 5'), ('DB', 'dynamic brake'), ('N6', 'notch 6'), ('N4', 'notch 4')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='line',
            name='rights',
        ),
        migrations.AddField(
            model_name='line',
            name='rights',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
