# Generated by Django 4.1.1 on 2023-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0041_rename_geometry_line_curvature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N2', 'notch 2'), ('N1', 'notch 1'), ('N3', 'notch 3'), ('N4', 'notch 4'), ('LI', 'idle'), ('DB', 'dynamic brake'), ('N5', 'notch 5'), ('N6', 'notch 6'), ('N7', 'notch 7'), ('N8', 'notch 8')], max_length=20),
        ),
        migrations.AlterField(
            model_name='yard',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
