# Generated by Django 4.1.1 on 2023-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0042_alter_emission_power_level_alter_yard_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N2', 'notch 2'), ('N1', 'notch 1'), ('LI', 'idle'), ('N6', 'notch 6'), ('N4', 'notch 4'), ('N3', 'notch 3'), ('N8', 'notch 8'), ('N7', 'notch 7'), ('N5', 'notch 5'), ('DB', 'dynamic brake')], max_length=20),
        ),
    ]
