# Generated by Django 4.1.1 on 2023-12-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0043_line_length_alter_emission_power_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N6', 'notch 6'), ('N5', 'notch 5'), ('N3', 'notch 3'), ('DB', 'dynamic brake'), ('N1', 'notch 1'), ('LI', 'idle'), ('N4', 'notch 4'), ('N8', 'notch 8'), ('N2', 'notch 2'), ('N7', 'notch 7')], max_length=20),
        ),
    ]
