# Generated by Django 4.1.1 on 2023-12-08 14:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0044_alter_emission_power_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='xyz',
            new_name='elevation',
        ),
        migrations.AddField(
            model_name='line',
            name='xy',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N6', 'notch 6'), ('N5', 'notch 5'), ('N8', 'notch 8'), ('LI', 'idle'), ('N3', 'notch 3'), ('DB', 'dynamic brake'), ('N7', 'notch 7'), ('N4', 'notch 4'), ('N1', 'notch 1'), ('N2', 'notch 2')], max_length=20),
        ),
    ]
