# Generated by Django 4.1.1 on 2023-12-08 20:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0045_rename_xyz_line_elevation_line_xy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='distance',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='net',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N6', 'notch 6'), ('LI', 'idle'), ('N1', 'notch 1'), ('N5', 'notch 5'), ('N8', 'notch 8'), ('DB', 'dynamic brake'), ('N7', 'notch 7'), ('N3', 'notch 3'), ('N2', 'notch 2'), ('N4', 'notch 4')], max_length=20),
        ),
    ]
