# Generated by Django 4.1.1 on 2023-12-19 21:31

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0046_line_distance_line_net_alter_emission_power_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='max_speed',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N7', 'notch 7'), ('N6', 'notch 6'), ('DB', 'dynamic brake'), ('N5', 'notch 5'), ('N4', 'notch 4'), ('N2', 'notch 2'), ('N1', 'notch 1'), ('N8', 'notch 8'), ('N3', 'notch 3'), ('LI', 'idle')], max_length=20),
        ),
    ]
