# Generated by Django 4.1.1 on 2024-01-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0047_line_max_speed_alter_emission_power_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('LI', 'idle'), ('N2', 'notch 2'), ('N7', 'notch 7'), ('N1', 'notch 1'), ('N3', 'notch 3'), ('DB', 'dynamic brake'), ('N5', 'notch 5'), ('N6', 'notch 6'), ('N8', 'notch 8'), ('N4', 'notch 4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ltdresults',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locomotives.route2'),
        ),
    ]
