# Generated by Django 4.1.1 on 2024-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0049_alter_emission_power_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N6', 'notch 6'), ('N3', 'notch 3'), ('LI', 'idle'), ('N1', 'notch 1'), ('N2', 'notch 2'), ('N5', 'notch 5'), ('N7', 'notch 7'), ('N4', 'notch 4'), ('DB', 'dynamic brake'), ('N8', 'notch 8')], max_length=20),
        ),
    ]
