# Generated by Django 4.1.1 on 2024-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0050_alter_emission_power_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('DB', 'dynamic brake'), ('N4', 'notch 4'), ('N6', 'notch 6'), ('N7', 'notch 7'), ('N8', 'notch 8'), ('N3', 'notch 3'), ('N5', 'notch 5'), ('N1', 'notch 1'), ('N2', 'notch 2'), ('LI', 'idle')], max_length=20),
        ),
    ]
