# Generated by Django 4.1.1 on 2024-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locomotives', '0051_alter_emission_power_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='charge',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='emission',
            name='power_level',
            field=models.CharField(choices=[('N5', 'notch 5'), ('DB', 'dynamic brake'), ('N3', 'notch 3'), ('N2', 'notch 2'), ('N7', 'notch 7'), ('N1', 'notch 1'), ('LI', 'idle'), ('N6', 'notch 6'), ('N8', 'notch 8'), ('N4', 'notch 4')], max_length=20),
        ),
    ]
