version: '3.9'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/notebooks
