psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
create USER ${SCORE_USER} with password '${SCORE_PASSWORD}';
create DATABASE ${SCORE_DB} with owner ${SCORE_USER};
GRANT ALL PRIVILEGES ON DATABASE ${SCORE_DB} TO ${SCORE_USER};
EOSQL


