version: '3.8'

services:
  web:
    build: ./locomotives
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./locomotives/:/usr/src/locomotives/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    # user: "26:26" # run as postgres user
    build:
      context: ./db
      dockerfile: ./Dockerfile
    image: score_db
    container_name: score_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=score123
      - SCORE_USER=locuser
      - SCORE_PASSWORD=locteam
      - SCORE_DB=locomotives
      # - POSTGRES_PASSWORD=locteam
      # - POSTGRES_DB=locomotives
  redis:
    build: ./redis
    ports: 
      - "6379:6379"
  celery:
    # restart: always
    build: ./locomotives
    image: score_worker
    volumes: 
      - ./locomotives/:/usr/src/locomotives/
    command: celery -A config worker -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

  
volumes:
  pg_data: